spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus


server:
  port: 8085